version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba123
      POSTGRES_DB: nestdbb
    ports:
      - 5498:5432
